# pytorch_lightning==2.0.2
seed_everything: true
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 1
        monitor: valid_loss
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: callbacks.print.MyPrintingCallback
      init_args:
        p: 10
    #- class_path: pytorch_lightning.callbacks. GPUStatsMonitor
    #  init_args:
    #    memory_utilization: True
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger: true
  max_epochs: 10
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  log_every_n_steps: 10
model:
  network:
    class_path: model.nets.TwoLayerNet
    init_args:
      hidden_dim: 12
      out_dim: 10
  learning_rate: 0.02
data:
  class_path: data.MNISTDataModule
  init_args:
    data_dir: datasets/mnist
    batch_size: 4
ckpt_path: null
